/*
 * PlayersJPanel.java
 *
 * Created on 17.01.2011, 10:21:02
 */
package hunter;

/**
 * @version 0.1.0
 * @author Pushkarev Andrey [fealaer@gmail.com]
 */
public class PlayersJPanel extends javax.swing.JPanel {

    /** Creates new form PlayersJPanel */
    public PlayersJPanel() {
        initComponents();
        playersList.addItem(System.getProperty("user.name"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerName = new javax.swing.JTextField();
        addPlayer = new javax.swing.JButton();
        playersList = new javax.swing.JComboBox();
        New = new javax.swing.JLabel();
        players = new javax.swing.JLabel();
        toServers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 300));

        playerName.setText("Player Name");

        addPlayer.setText("Add");
        addPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerActionPerformed(evt);
            }
        });

        New.setText("New Player:");

        players.setText("Players:");

        toServers.setText("Next >>");
        toServers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toServersActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose Player");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(New, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerName, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                    .addComponent(addPlayer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toServers, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(players, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(playersList, 0, 280, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(players))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(New))
                .addGap(18, 18, 18)
                .addComponent(addPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(toServers)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerActionPerformed
        String newPlayerName = playerName.getText();
        if (newPlayerName == null
                || newPlayerName.equalsIgnoreCase("Player Name")
                || newPlayerName.equalsIgnoreCase("")) {
            return;

        }
        playersList.addItem(newPlayerName);
        playersList.setSelectedItem(newPlayerName);
}//GEN-LAST:event_addPlayerActionPerformed

    private void toServersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toServersActionPerformed
        GameFrame frame = (GameFrame) Main.getFrame();
        frame.changePanelsActivity(this, "ServersJPanel");
}//GEN-LAST:event_toServersActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel New;
    private javax.swing.JButton addPlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField playerName;
    private javax.swing.JLabel players;
    private javax.swing.JComboBox playersList;
    private javax.swing.JButton toServers;
    // End of variables declaration//GEN-END:variables
}
