/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerFrame.java
 *
 * Created on Jan 16, 2011, 2:49:32 PM
 */

package hunter;

import javax.swing.JFrame;

/**
 *
 * @author fealaer
 */
public class PlayerFrame extends javax.swing.JFrame {

    /** Creates new form PlayerFrame */
    public PlayerFrame() {
        initComponents();
		playersList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "fealaer" }));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerName = new javax.swing.JTextField();
        players = new javax.swing.JLabel();
        New = new javax.swing.JLabel();
        playersList = new javax.swing.JComboBox();
        addPlayer = new javax.swing.JButton();
        toServers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerName.setText("Player Name");

        players.setText("Players:");

        New.setText("New Player:");

        playersList.setNextFocusableComponent(playerName);

        addPlayer.setText("Add");
        addPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerActionPerformed(evt);
            }
        });

        toServers.setText("Next >>");
        toServers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toServersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(players)
                            .addComponent(New))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerName, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(playersList, 0, 228, Short.MAX_VALUE)))
                    .addComponent(addPlayer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toServers, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(players)
                    .addComponent(playersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(New)
                    .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(toServers)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void addPlayerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addPlayerActionPerformed
	{//GEN-HEADEREND:event_addPlayerActionPerformed
		String newPlayerName = playerName.getText();
		if (newPlayerName == null ||
			newPlayerName.equalsIgnoreCase("Player Name") ||
			newPlayerName.equalsIgnoreCase("")
			)
		{
			return;

		}
		playersList.addItem(newPlayerName);
		playersList.setSelectedItem(newPlayerName);
	}//GEN-LAST:event_addPlayerActionPerformed

	private void toServersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toServersActionPerformed
	{//GEN-HEADEREND:event_toServersActionPerformed
		JFrame frame = Hunter.getFrame("ServersFrame");
		System.out.print(frame);
		if (frame == null)
		{
			frame = new ServersFrame();
			frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
			Hunter.setFrame("ServersFrame", frame);
		}
		frame.setLocation(this.getLocation());
		this.setVisible(false);
		frame.setVisible(true);
	}//GEN-LAST:event_toServersActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel New;
    private javax.swing.JButton addPlayer;
    private javax.swing.JTextField playerName;
    private javax.swing.JLabel players;
    private javax.swing.JComboBox playersList;
    private javax.swing.JButton toServers;
    // End of variables declaration//GEN-END:variables

}
