/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerFrame.java
 *
 * Created on Jan 16, 2011, 2:49:32 PM
 */

package hunter;

import javax.swing.JFrame;

/**
 *
 * @author fealaer
 */
public class ServersFrame extends javax.swing.JFrame {

    /** Creates new form PlayerFrame */
    public ServersFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverIpPort = new javax.swing.JTextField();
        servers = new javax.swing.JLabel();
        newServer = new javax.swing.JLabel();
        serversList = new javax.swing.JComboBox();
        addServer = new javax.swing.JButton();
        toGames = new javax.swing.JButton();
        toPlayers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        serverIpPort.setText("IP[:port]");

        servers.setText("Servers:");

        newServer.setText("New Server:");

        serversList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addServer.setText("Add");
        addServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addServerActionPerformed(evt);
            }
        });

        toGames.setText("Next >>");
        toGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toGamesActionPerformed(evt);
            }
        });

        toPlayers.setText("<< Prev");
        toPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toPlayersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(servers)
                            .addComponent(newServer))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serverIpPort, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(serversList, 0, 226, Short.MAX_VALUE)))
                    .addComponent(addServer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(toPlayers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                        .addComponent(toGames)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(servers)
                    .addComponent(serversList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newServer)
                    .addComponent(serverIpPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toGames)
                    .addComponent(toPlayers))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void addServerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addServerActionPerformed
	{//GEN-HEADEREND:event_addServerActionPerformed
		GameFrame frame = new GameFrame();
		frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
	}//GEN-LAST:event_addServerActionPerformed

	private void toGamesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toGamesActionPerformed
	{//GEN-HEADEREND:event_toGamesActionPerformed
		ServersFrame frame = new ServersFrame();
		frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
	}//GEN-LAST:event_toGamesActionPerformed

	private void toPlayersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toPlayersActionPerformed
	{//GEN-HEADEREND:event_toPlayersActionPerformed
		JFrame frame = Hunter.getFrame("PlayersFrame");
		frame.setLocation(this.getLocation());
		this.setVisible(false);
		frame.setVisible(true);
	}//GEN-LAST:event_toPlayersActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addServer;
    private javax.swing.JLabel newServer;
    private javax.swing.JTextField serverIpPort;
    private javax.swing.JLabel servers;
    private javax.swing.JComboBox serversList;
    private javax.swing.JButton toGames;
    private javax.swing.JButton toPlayers;
    // End of variables declaration//GEN-END:variables

}
