/*
 * ServersJPanel.java
 *
 * Created on 17.01.2011, 10:30:21
 */

package hunter;

import java.awt.Component;
import javax.swing.JPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
public class ServersJPanel extends javax.swing.JPanel {

    /** Creates new form ServersJPanel */
    public ServersJPanel() {
        initComponents();
        serversList.addItem("localhost:666999");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serversList = new javax.swing.JComboBox();
        newServer = new javax.swing.JLabel();
        servers = new javax.swing.JLabel();
        addServer = new javax.swing.JButton();
        toGames = new javax.swing.JButton();
        serverIpPort = new javax.swing.JTextField();
        toPlayers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 300));

        newServer.setText("New Game:");

        servers.setText("Servers:");

        addServer.setText("Add");
        addServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addServerActionPerformed(evt);
            }
        });

        toGames.setText("Next >>");
        toGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toGamesActionPerformed(evt);
            }
        });

        serverIpPort.setText("Ip:port");
        serverIpPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverIpPortActionPerformed(evt);
            }
        });

        toPlayers.setText("<< Prev");
        toPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toPlayersActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose Server");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newServer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serverIpPort, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toPlayers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                        .addComponent(toGames))
                    .addComponent(addServer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(servers, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serversList, 0, 264, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serversList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servers))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverIpPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newServer))
                .addGap(27, 27, 27)
                .addComponent(addServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toPlayers)
                    .addComponent(toGames))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addServerActionPerformed
        String newServerIpPort = serverIpPort.getText();
        if (newServerIpPort == null ||
                newServerIpPort.equalsIgnoreCase("IP[:port]") ||
                newServerIpPort.equalsIgnoreCase("")
                ) {
            return;

        }
        serversList.addItem(newServerIpPort);
        serversList.setSelectedItem(newServerIpPort);
}//GEN-LAST:event_addServerActionPerformed

    private void toGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toGamesActionPerformed
        GameFrame frame = (GameFrame) Main.getFrame();
        //frame.changePanelsActivity(this, "GamesJPanel");
        Component panel = new PlayArea (50, frame.getWidth(), frame.getHeight() - 80, "img/backgrounds/bg1_sign.png");
        frame.add(panel);
        this.setVisible(false);
}//GEN-LAST:event_toGamesActionPerformed

    private void toPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toPlayersActionPerformed
        GameFrame frame = (GameFrame) Main.getFrame();
        frame.changePanelsActivity(this, "PlayersJPanel");
}//GEN-LAST:event_toPlayersActionPerformed

    private void serverIpPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverIpPortActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_serverIpPortActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel newServer;
    private javax.swing.JTextField serverIpPort;
    private javax.swing.JLabel servers;
    private javax.swing.JComboBox serversList;
    private javax.swing.JButton toGames;
    private javax.swing.JButton toPlayers;
    // End of variables declaration//GEN-END:variables

}
